// Generated by CoffeeScript 2.5.1
(function() {
  var debugmodule;

  debugmodule = {
    name: "debugmodule"
  };

  //#############################################################################
  debugmodule.initialize = function() {};

  
  //#############################################################################
  // console.log "debugmodule.initialize - nothing to do"
  debugmodule.modulesToDebug = {
    unbreaker: true
  };

  // cliargumentsmodule: true
  // configmodule: true
  // gitmodule: true
  // mainprocessmodule: true
  // pathhandlermodule: true
  // pullcommandmodule: true
  // pushcommandmodule: true
  // startupmodule: true
  module.exports = debugmodule;

}).call(this);
