// Generated by CoffeeScript 2.5.1
(function() {
  var log, mainprocessmodule, olog, ostr, pathHandler, print, pullCommand, pushCommand;

  mainprocessmodule = {
    name: "mainprocessmodule"
  };

  //region modulesFromEnvironment
  pathHandler = null;

  pushCommand = null;

  pullCommand = null;

  //endregion

  //region logPrintFunctions
  //#############################################################################
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["mainprocessmodule"] != null) {
      console.log("[mainprocessmodule]: " + arg);
    }
  };

  olog = function(o) {
    return log("\n" + ostr(o));
  };

  ostr = function(o) {
    return JSON.stringify(o, null, 4);
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion
  //#############################################################################
  mainprocessmodule.initialize = function() {
    log("mainprocessmodule.initialize");
    pathHandler = allModules.pathhandlermodule;
    pushCommand = allModules.pushcommandmodule;
    pullCommand = allModules.pullcommandmodule;
  };

  
  //region internalFunctions
  //endregion

  //region exposedFunctions
  mainprocessmodule.execute = async function(e) {
    log("mainprocessmodule.execute");
    pathHandler.digestArgument(e.path);
    switch (e.command) {
      case "pull":
        await pullCommand.execute();
        break;
      case "push":
        await pushCommand.execute(e.message);
        break;
      default:
        throw "Unknown Command: " + e.command;
    }
  };

  //endregion
  module.exports = mainprocessmodule;

}).call(this);
