// Generated by CoffeeScript 2.5.1
(function() {
  var Modules;

  Modules = {
    cliargumentsmodule: require("./cliargumentsmodule"),
    configmodule: require("./configmodule"),
    debugmodule: require("./debugmodule"),
    gitmodule: require("./gitmodule"),
    mainprocessmodule: require("./mainprocessmodule"),
    pathhandlermodule: require("./pathhandlermodule"),
    pullcommandmodule: require("./pullcommandmodule"),
    pushcommandmodule: require("./pushcommandmodule"),
    startupmodule: require("./startupmodule")
  };

  module.exports = Modules;

}).call(this);
