// Generated by CoffeeScript 2.5.1
(function() {
  var homedir, log, os, pathModule, pathhandlermodule, print, resolveHomeDir;

  pathhandlermodule = {
    name: "pathhandlermodule"
  };

  //region modulesFromTheEnvironment#
  //region node_modules
  pathModule = require("path");

  os = require("os");

  //endregion
  //endregion

  //region printLogFunctions
  //#############################################################################
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["pathhandlermodule"] != null) {
      console.log("[pathhandlermodule]: " + arg);
    }
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion
  //#############################################################################
  pathhandlermodule.initialize = function() {
    log("pathhandlermodule.initialize");
  };

  //region internal
  //region internalProperties
  homedir = os.homedir();

  //endregion

  //region internalFunctions
  resolveHomeDir = function(path) {
    log("resolveHomeDir");
    if (!path) {
      return;
    }
    if (path[0] === "~") {
      path = path.replace("~", homedir);
    }
    return path;
  };

  //endregion
  //endregion

  //region exposed
  //region exposedProperties
  pathhandlermodule.basePath = "";

  //endregion

  //region exposedFunctions
  pathhandlermodule.digestArgument = function(providedPath) {
    log("pathhandlermodule.digestArgument");
    if (!providedPath) {
      providedPath = process.cwd();
    }
    if (!pathModule.isAbsolute(providedPath)) {
      providedPath = resolveHomeDir(providedPath);
      providedPath = pathModule.resolve(providedPath);
    }
    pathhandlermodule.basePath = providedPath;
  };

  pathhandlermodule.resolve = function(base, further) {
    log("pathhandlermodule.resolve");
    return pathModule.resolve(base, further);
  };

  //endregion
  //endregion
  module.exports = pathhandlermodule;

}).call(this);
